apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-external-secret
  namespace: object-storage
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  
  target:
    name: seaweedfs-s3-secret
    template:
      type: Opaque
      data:
        seaweedfs_s3_config: |
          {
            "identities": [{
              "name": "tre-admin",
              "credentials": [{
                "accessKey": "{{ .accessKey }}",
                "secretKey": "{{ .secretKey }}"
              }],
              "actions": ["Admin", "Read", "Write"]
            }]
          }
  
  data:
    - secretKey: accessKey
      remoteRef:
        key: seaweedfs-s3-credentials  # Same for all envs
        property: access-key
    
    - secretKey: secretKey
      remoteRef:
        key: seaweedfs-s3-credentials  # Same for all envs
        property: secret-key