apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rwo-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "ReadWriteOnce - Single pod read-write access"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataLocality: "best-effort"
