apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cr8tor
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/umccr/k8tre.git
              revision: main
              directories:
                - path: apps/cr8tor/envs/*
          - clusters:
              selector:
                matchLabels:
                  environment: "{{index .path.segments 3}}"
                matchExpressions:
                  - key: skip-cr8tor
                    operator: NotIn
                    values: ["true"]
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{.nameNormalized}}"
      annotations:
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .path.segments 3}}"
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      source:
        repoURL: https://github.com/umccr/k8tre.git
        targetRevision: main
        path: "{{.path.path}}"
        plugin:
          name: kustomize-with-envsubst-v1.0
          env:
            - name: ENVIRONMENT
              value: "{{.metadata.labels.environment}}"
            - name: DOMAIN
              value: "{{index .metadata.labels \"external-domain\"}}"
      destination:
        server: "{{.server}}"
        namespace: cr8tor
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
