apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-admin
  namespace: gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-patch-role
  namespace: gateway
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-patch-rolebinding
  namespace: gateway
subjects:
- kind: ServiceAccount
  name: gateway-admin
  namespace: gateway
roleRef:
  kind: Role
  name: gateway-patch-role
  apiGroup: rbac.authorization.k8s.io
