apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea-route
  namespace: gitea
spec:
  parentRefs:
    - name: internal-gateway
      namespace: gateway
  hostnames:
    - "gitea.k8tre.${ENVIRONMENT}.${DOMAIN}"
  rules:
    - backendRefs:
        - name: gitea-http
          namespace: gitea
          port: 3000
