apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cr8tor-microserviceapikey-secret
  # namespace: cr8tor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore to fetch the secrets from
  target:
    name: cr8tor-microserviceapikey-secret # name of the k8s Secret to be created
  data:
    - secretKey: approvalserviceapikey # pragma: allowlist secret
      remoteRef:
        key: cr8tor-microserviceapikey-secret
        property: approvalserviceapikey
    - secretKey: metadataserviceapikey # pragma: allowlist secret
      remoteRef:
        key: cr8tor-microserviceapikey-secret
        property: metadataserviceapikey
    - secretKey: publishserviceapikey # pragma: allowlist secret
      remoteRef:
        key: cr8tor-microserviceapikey-secret
        property: publishserviceapikey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cr8tor-secret
  # namespace: cr8tor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore to fetch the secrets from
  target:
    name: cr8tor-secret # name of the k8s Secret to be created
  data:
    - secretKey: mysql-rfam-public-username # pragma: allowlist secret
      remoteRef:
        key: cr8tor-secret
        property: mysql-rfam-public-username
    - secretKey: mysql-rfam-public-password # pragma: allowlist secret
      remoteRef:
        key: cr8tor-secret
        property: mysql-rfam-public-password
    - secretKey: postgresql-pgsqldb-lth-username # pragma: allowlist secret
      remoteRef:
        key: cr8tor-secret
        property: postgresql-pgsqldb-lth-username
    - secretKey: postgresql-pgsqldb-lth-password # pragma: allowlist secret
      remoteRef:
        key: cr8tor-secret
        property: postgresql-pgsqldb-lth-password
