apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |
    {
      "tenantId": "30a82846-a29e-4b6b-af27-9b19418ee1b3",
      "subscriptionId": "443fc06f-050e-4794-83d8-eaeee691d453",
      "resourceGroup": "rg-kare-con-uks-dns",
      "useWorkloadIdentityExtension": true
    }
