apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xk8tre-tls
  namespace: keycloak
spec:
  secretName: keycloak.${ENVIRONMENT}.${DOMAIN}-tls # pragma: allowlist secret
  privateKey:
    rotationPolicy: Always
  commonName: keycloak.${ENVIRONMENT}.${DOMAIN}
  dnsNames:
    - keycloak.${ENVIRONMENT}.${DOMAIN}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
