# Updates CoreDNS if IPs don't match
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-monitor-script
  namespace: kube-system
data:
  monitor-dns.sh: |-
    #!/bin/sh
    set -e

    # Get upstream DNS
    if [ -f /shared/upstream-dns ]; then
      UPSTREAM_DNS=$(cat /shared/upstream-dns)
    else
      echo "ERROR: Couldn't get upstream DNS"
      exit 1
    fi

    CURRENT_IP=$(kubectl get svc kare-dns-coredns -n kare-dns -o jsonpath='{.spec.clusterIP}' 2>/dev/null || echo "")

    if [ -z "$CURRENT_IP" ]; then
      echo "ERROR: kare-dns service not found"
      exit 1
    fi

    # Get IP from CoreDNS
    CONFIGURED_IP=$(kubectl get cm coredns -n kube-system -o jsonpath='{.data.Corefile}' | \
      grep -A 2 "k8tre.${ENVIRONMENT}.${DOMAIN}:53" | grep "forward" | awk '{print $3}' | cut -d: -f1)

    echo "Current kare-dns IP: $CURRENT_IP"
    echo "Configured CoreDNS IP: $CONFIGURED_IP"

    # Update if there's a mismatch
    if [ "$CURRENT_IP" = "$CONFIGURED_IP" ]; then
      echo "DNS configuration is correct, no action needed"
      exit 0
    fi

    echo "IP mismatch detected! Updating CoreDNS..."
    cat > /tmp/new-corefile << 'COREFILE'
    k8tre.${ENVIRONMENT}.${DOMAIN}:53 {
        errors
        forward . ${CURRENT_IP}:53
    }
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
            ttl 60
            reload 15s
            fallthrough
        }
        prometheus :9153
        forward . ${UPSTREAM_DNS}
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
    COREFILE

    # Substitute env
    sed -i "s/\${ENVIRONMENT}/$ENVIRONMENT/g; s/\${DOMAIN}/$DOMAIN/g; s/\${CURRENT_IP}/$CURRENT_IP/g; s/\${UPSTREAM_DNS}/$UPSTREAM_DNS/g" /tmp/new-corefile

    # Update and restart
    kubectl patch configmap coredns -n kube-system --patch "{\"data\":{\"Corefile\":\"$(cat /tmp/new-corefile | sed 's/$/\\n/' | tr -d '\n' | sed 's/\\n$//')\"}}"
    kubectl rollout restart deployment/coredns -n kube-system
    echo "CoreDNS updated successfully"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-monitor
  namespace: kube-system
spec:
  schedule: "*/2 * * * *"  # every 2 mins
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: coredns
          restartPolicy: OnFailure
          initContainers:
          - name: detect-upstream-dns
            image: alpine/k8s:1.31.1
            command:
            - /bin/sh
            - -c
            - |
              echo "Detecting upstream DNS"
              DETECTED_DNS=""
              TEST_DOMAIN="dns.google"

              # Default gateway
              GATEWAY_DNS=$(ip route | grep default | awk '{print $3}' | head -1)
              if [ -n "$GATEWAY_DNS" ] && echo "$GATEWAY_DNS" | grep -Eq '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'; then
                if timeout 2 nslookup "$TEST_DOMAIN" "$GATEWAY_DNS" >/dev/null 2>&1; then
                  DETECTED_DNS="$GATEWAY_DNS"
                  echo "Using gateway: $GATEWAY_DNS"
                fi
              fi

              # systemd-resolved
              if [ -z "$DETECTED_DNS" ] && [ -f /run/systemd/resolve/resolv.conf ]; then
                SYSTEMD_DNS=$(grep "^nameserver" /run/systemd/resolve/resolv.conf 2>/dev/null | head -1 | awk '{print $2}')
                if [ -n "$SYSTEMD_DNS" ]; then
                  if timeout 2 nslookup "$TEST_DOMAIN" "$SYSTEMD_DNS" >/dev/null 2>&1; then
                    DETECTED_DNS="$SYSTEMD_DNS"
                    echo "Using systemd-resolved: $SYSTEMD_DNS"
                  fi
                fi
              fi

              # /etc/resolv.conf
              if [ -z "$DETECTED_DNS" ]; then
                RESOLV_DNS=$(grep "^nameserver" /etc/resolv.conf 2>/dev/null | grep -v "127.0.0.53" | head -1 | awk '{print $2}')
                if [ -n "$RESOLV_DNS" ]; then
                  if timeout 2 nslookup "$TEST_DOMAIN" "$RESOLV_DNS" >/dev/null 2>&1; then
                    DETECTED_DNS="$RESOLV_DNS"
                    echo "Using resolv.conf: $RESOLV_DNS"
                  fi
                fi
              fi

              if [ -z "$DETECTED_DNS" ]; then
                echo "WARNING: using 8.8.8.8"
                DETECTED_DNS="8.8.8.8"
              fi

              echo "$DETECTED_DNS" > /shared/upstream-dns
            volumeMounts:
            - name: shared-data
              mountPath: /shared
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
          containers:
          - name: monitor
            image: alpine/k8s:1.31.1
            command: ["/bin/sh", "/scripts/monitor-dns.sh"]
            env:
            - name: ENVIRONMENT
              value: "${ENVIRONMENT}"
            - name: DOMAIN
              value: "${DOMAIN}"
            volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: shared-data
              mountPath: /shared
              readOnly: true
            resources:
              requests:
                memory: "16Mi"
                cpu: "5m"
              limits:
                memory: "32Mi"
                cpu: "20m"
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
          volumes:
          - name: scripts
            configMap:
              name: dns-monitor-script
              defaultMode: 0755
          - name: tmp
            emptyDir: {}
          - name: shared-data
            emptyDir: {}
          hostNetwork: true
          dnsPolicy: Default
