apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-json-secret
  namespace: jupyterhub
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore to fetch the secrets from
  target:
    name: guacamole-json-secret # name of the k8s Secret to be created
  data:
    - secretKey: GUACAMOLE_JSON_SECRET_KEY # pragma: allowlist secret
      remoteRef:
        key: guacamole-json-secret
        property: GUACAMOLE_JSON_SECRET_KEY
