apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-secret
  namespace: jupyterhub
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore to fetch the secrets from
  target:
    name: jupyterhub-secret # name of the k8s Secret to be created
  data:
    - secretKey: hub.services.guacamole.apiToken # pragma: allowlist secret
      remoteRef:
        key: jupyterhub-secret
        property: hub.services.guacamole.apiToken
