approvalService:
  image: "ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-approval-service:0.1.65"
  volumes:
  - name: secrets-store-inline
    projected:
      defaultMode: 0444
      sources:
      - secret:
          name: cr8tor-microserviceapikey-secret
      - secret:
          name: cr8tor-secret
  env:
    - name: ENVIRONMENT
      value: "${ENVIRONMENT}"

metadataService:
  image: "ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-metadata-service:0.1.65"
  volumes:
  - name: secrets-store-inline
    projected:
      defaultMode: 0444
      sources:
      - secret:
          name: cr8tor-microserviceapikey-secret
      - secret:
          name: cr8tor-secret
  env:
    - name: ENVIRONMENT
      value: "${ENVIRONMENT}"

publishService:
  image: "ghcr.io/lsc-sde-crates/cr8tor-publisher/cr8tor-publish-service:0.1.65"
  volumes:
  - name: secrets-store-inline
    projected:
      defaultMode: 0444
      sources:
      - secret:
          name: cr8tor-microserviceapikey-secret
      - secret:
          name: cr8tor-secret
  env:
    - name: ENVIRONMENT
      value: "${ENVIRONMENT}"

ingress:
  # Using HTTPRoute/cr8tor-approval-route
  enabled: false

storage: 
  k8tre:
    env: TARGET_STORAGE_ACCOUNT_K8TRE_SDE_MNT_PATH
    mountPath: /home/appuser/outputs/k8tre
    pvcs:
      staging:
        name: k8tre-staging
        create: true
        storageClassName: rwx-default
        accessModes:
        - ReadWriteMany

      production:
        name: k8tre-prod
        create: true
        storageClassName: rwx-default
        accessModes:
        - ReadWriteMany
    lsc:
      env: TARGET_STORAGE_ACCOUNT_LSC_SDE_MNT_PATH
      mountPath: /home/appuser/outputs/lsc
      pvcs:
        staging:
          name: lsc-staging
          create: true
          storageClassName: rwx-default
          accessModes:
          - ReadWriteMany

        production:
          name: lsc-prod
          create: true
          storageClassName: rwx-default
          accessModes:
          - ReadWriteMany
  nw:
    env: TARGET_STORAGE_ACCOUNT_NW_SDE_MNT_PATH
    mountPath: /home/appuser/outputs/nw
    pvcs:
      staging:
        name: nw-staging
        create: true
        storageClassName: rwx-default
        accessModes:
        - ReadWriteMany

      production:
        name: nw-prod
        create: true
        storageClassName: rwx-default
        accessModes:
        - ReadWriteMany

    
