apiVersion: batch/v1
kind: Job
metadata:
  name: gateway-srv-patch
  namespace: gateway
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: gateway-admin
      containers:
      - name: kubectl
        image: alpine/k8s:1.31.1
        env:
        - name: ENVIRONMENT
          value: ${ENVIRONMENT}
        - name: EXTERNAL_DOMAIN
          value: ${DOMAIN}
        command:
          - /bin/sh
          - -c
          - |
            until kubectl get svc cilium-gateway-internal-gateway -n gateway; do
              echo "Waiting for cilium-gateway-internal-gateway..."
              sleep 5
            done

            kubectl patch svc cilium-gateway-internal-gateway -n gateway \
            --type=merge \
            -p "{
              \"metadata\": {
                \"annotations\": {
                  \"service.beta.kubernetes.io/azure-load-balancer-internal\": \"true\",
                  \"service.beta.kubernetes.io/azure-load-balancer-internal-subnet\": \"snet-clusteringressservices\",
                  \"service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path\": \"/healthz\",
                  \"external-dns.alpha.kubernetes.io/hostname\": \"*.k8tre.${ENVIRONMENT}.${EXTERNAL_DOMAIN}\"
                }
              }
            }"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-admin
  namespace: gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-patch-role
  namespace: gateway
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-patch-rolebinding
  namespace: gateway
subjects:
- kind: ServiceAccount
  name: gateway-admin
  namespace: gateway
roleRef:
  kind: Role
  name: gateway-patch-role
  apiGroup: rbac.authorization.k8s.io
