apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rwx-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    description: "ReadWriteMany - Azure File Share"
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  storageAccount: stgk8trecore${ENVIRONMENT}
  resourceGroup: rg-k8tre-${ENVIRONMENT}-uks-aks
  skuName: Standard_LRS
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nosharesock
  - cache=strict
  - actimeo=30
  - nobrl
