provider:
  name: aws

aws:
  # Only modify private Route53 zone
  # This means we can have split DNS (public and private zones) without needing to pass
  # the Zone ID to the operator, just the domain is enough
  zoneType: public

env:
  - name: AWS_DEFAULT_REGION
    value: ap-southeast-2

serviceAccount:
  create: true
  name: externaldns-sa

sources:
  - gateway-httproute
  # - gateway-tlsroute

policy: sync
txtOwnerId: externaldns
