apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
  - ${METALLB_IP_RANGE} # Configured via cluster label metallb-ip-range
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
spec:
  ipAddressPools:
  - default-pool
