apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-letsencrypt-egress
  namespace: cert-manager
spec:
  endpointSelector:
    matchLabels:
      app: cert-manager
  egress:
    - toFQDNs:
        - matchPattern: "*.letsencrypt.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP