apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# TODO: enable ACME Lets Encrypt certificates, or use ACM on the load balancer
# https://cert-manager.io/docs/configuration/acme/dns01/route53/
