apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-dns-egress
  namespace: external-dns
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  egress:
    - toCIDR:
        - "0.0.0.0/0"
    # DNS to CoreDNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            kubernetes.io/metadata.name: kube-system
      toPorts:
        - ports:
            - { port: "53", protocol: UDP }
            - { port: "53", protocol: TCP }
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-coredns-egress-dns-external-dns
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
  egress:
    - toCIDRSet:
        - cidr: "0.0.0.0/0"
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
  ingress:
    - fromEntities:
        - cluster
        - host
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
