apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-dns-egress
  namespace: external-dns
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  egress:
    - toCIDR:
        - "0.0.0.0/0"
