apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  # annotations:
  #   external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    aws:
      service: ParameterStore
      region: ${REGION}
      # Note serviceAccountRef must not be set with EKS Pod Identity
